name       : x42-plugins
version    : '20220327'
release    : 8
source     :
    - https://gareus.org/misc/x42-plugins/x42-plugins-20220327.tar.xz : 221b8fa939426c2c44c53e41f40bb8d91410978b0312fcfaf8786cb93d36295b
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Collection of LV2 plugins by x42-plugins.
description: |
    Collection of LV2 plugins by x42-plugins.
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(ftgl)
    - pkgconfig(glu)
    - pkgconfig(jack)
    - pkgconfig(lv2)
    - pkgconfig(pango)
    - pkgconfig(pixman-1)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - font-freefont-ttf
    - libltc-devel
    - zita-convolver-devel
build      : |
    %make
install    : |
    %make_install PREFIX=%PREFIX% LV2DIR=%PREFIX%/lib64/lv2
