name       : x42-plugins
version    : '20200714'
release    : 6
source     :
    - http://gareus.org/misc/x42-plugins/x42-plugins-20200714.tar.xz : 746fe07a561392ba8c9c5de75dd3881fcc1de0733f55880238a62378a72f60ab
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Collection of LV2 plugins by x42-plugins.
description: |
    Collection of LV2 plugins by x42-plugins.
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(ftgl)
    - pkgconfig(glu)
    - pkgconfig(jack)
    - pkgconfig(lv2)
    - pkgconfig(pango)
    - pkgconfig(pixman-1)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - font-freefont-ttf
    - libltc-devel
    - zita-convolver-devel
build      : |
    %make
install    : |
    %make_install PREFIX=%PREFIX% LV2DIR=%PREFIX%/lib64/lv2
