name       : x42-plugins
version    : '20200411'
release    : 5
source     :
    - http://gareus.org/misc/x42-plugins/x42-plugins-20200411.tar.xz : d2c07782896128873b1d6fd82e4730ef44cfe61e1cd730ee9e00b12f283ac778
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Collection of LV2 plugins by x42-plugins.
description: |
    Collection of LV2 plugins by x42-plugins.
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(ftgl)
    - pkgconfig(glu)
    - pkgconfig(jack)
    - pkgconfig(lv2)
    - pkgconfig(pango)
    - pkgconfig(pixman-1)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - font-freefont-ttf
    - libltc-devel
    - zita-convolver-devel
build      : |
    %make
install    : |
    %make_install PREFIX=%PREFIX% LV2DIR=%PREFIX%/lib64/lv2
