name       : x42-plugins
version    : 2.0.18
release    : 1
source     :
    - http://gareus.org/misc/x42-plugins/x42-plugins-20180812.tar.xz : bf25df6d7557a4c7b0374da4b0f829cd3baa53e457df210d4b5c4ca16efffc3f
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Collection of LV2 plugins by x42-plugins.
description: |
    Collection of LV2 plugins by x42-plugins.
builddeps  :
  - pkgconfig(cairo)
  - pkgconfig(fftw3)
  - pkgconfig(ftgl)
  - pkgconfig(gl)
  - pkgconfig(glu)
  - pkgconfig(jack)
  - pkgconfig(lv2)
  - pkgconfig(pango)
  - pkgconfig(pixman-1)
  - pkgconfig(samplerate)
  - pkgconfig(sndfile)
  - font-freefont-ttf
  - libltc-devel
  - libzita-convolver-devel
build      : |
  %make
install    : |
  %make_install PREFIX=%PREFIX% LV2DIR=%PREFIX%/lib64/lv2
