name       : x42-plugins
version    : '20191013'
release    : 2
source     :
    - http://gareus.org/misc/x42-plugins/x42-plugins-20191013.tar.xz : 4444f866bd95b8843dd2e812e5795fc3feefe28aa1b04906bacd68c0ea0a76a2
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Collection of LV2 plugins by x42-plugins.
description: |
    Collection of LV2 plugins by x42-plugins.
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(ftgl)
    - pkgconfig(glu)
    - pkgconfig(jack)
    - pkgconfig(lv2)
    - pkgconfig(pango)
    - pkgconfig(pixman-1)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - font-freefont-ttf
    - libltc-devel
    - zita-convolver-devel
build      : |
    %make
install    : |
    %make_install PREFIX=%PREFIX% LV2DIR=%PREFIX%/lib64/lv2
